### ISSUE TITLE
Running 'Firebase Use --ADD" Results In ENOTFOUND admin.firebase.com admin.firebase.com:443

### ISSUE THREAD

**Issue by JimLynchCodes** [lvivier/firebase-cli#4]
I was playing around with 'firebase use' and used the unalias command on my project (after adding a staging project I wanted to rename my default alias to "prod").

That worked, but now whenever I run firebase use --add:
`firebase use --add`

I get this error:
Error: Server Error. getaddrinfo ENOTFOUND admin.firebase.com admin.firebase.com:443

![cypherapp_ _-bash_ _87x24](https://cloud.githubusercontent.com/assets/5354163/21572580/a7d994b2-cea8-11e6-98b9-b2a5fc6e26a4.png)

**Comment by JimLynchCodes** [comment]
wait, is this the right repo to post this issue?

**Comment by lvivier** [comment]
@JimTheMan hey man! If you didn't see it already, the official repo is https://github.com/firebase/firebase-tools. This is just an old, unofficial project that's now dead.
